env_config:
  carla:
    host: "localhost"
    port: 2000
    resolution_x: 1280
    resolution_y: 720
    quality_level: "Epic"
    enable_rendering: True

  experiment:
    hero:
      blueprint: "vehicle.tesla.model3"
      sensors:
        camera_rgb:
          type: "sensor.camera.rgb"
          image_size_x: 288
          image_size_y: 216
          transform: 0,0,2.4,0,0,0
    background_activity:
      n_vehicles: [32, 64]
      n_walkers: [32, 64]
      tm_hybrid_mode: True


policy_config:
  emergency_brake: 1.0
  sampling_resolution: 2.0  # meters, for global route planning
  local_planner:
    target_speed: 20  # km/h
    follow_speed_limits: False
    sampling_radius: 2.0  # meters
    base_min_distance: 3.0  # meters
    max_throttle: 0.75
    max_brake: 0.3
    max_steering: 0.8


guider_config:
  base_tlight_threshold: 5.0  # meters
  base_vehicle_threshold: 5.0  # meters
  emergency_brake: 1.0
  ignore_traffic_lights: False
  ignore_stop_signs: False
  ignore_vehicles: False
  sampling_resolution: 2.0  # meters, for global route planning
  local_planner:
    target_speed: 20  # km/h
    follow_speed_limits: False
    sampling_radius: 2.0  # meters
    base_min_distance: 3.0  # meters
    max_throttle: 0.75
    max_brake: 0.3
    max_steering: 0.8
    lateral_pid: [ 1.95, 0.05, 0.2 ]
    longitudinal_pid: [ 1.0, 0.05, 0 ]
    offset: 0


trainer_config:
  gamma: 0.99  # reward discount
  alpha: 0.2  # entropy weight
  polyak: 0.995  # synchronize weight
  lr_il: 0.001
  loss_weights: [1, 1, 1, 1, 1]
  lr_rl_actor: 0.001
  lr_rl_critic: 0.001


total_il_epoch: 3
total_rl_epoch: 128
il_batch_size: 1
il_horizon: 32
rl_batch_size: 16
debug: True
seed: null